<a href="https://colab.research.google.com/github/gundlapalliLokeshreddy/PDS_15_1676/blob/main/Lab_3_b15_1676.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

add_result = np.add(A, B)
sub_result = np.subtract(A, B)

print("\nMatrix Addition:\n", add_result)
print("\nMatrix Subtraction:\n", sub_result)

print("\nManual Check (A[0,0] + B[0,0]):", A[0,0] + B[0,0])
print("Manual Check (A[0,0] - B[0,0]):", A[0,0] - B[0,0])


Matrix A:
 [[6 9 7]
 [2 4 1]
 [4 8 1]]
Matrix B:
 [[2 2 5]
 [5 3 9]
 [9 1 4]]

Matrix Addition:
 [[ 8 11 12]
 [ 7  7 10]
 [13  9  5]]

Matrix Subtraction:
 [[ 4  7  2]
 [-3  1 -8]
 [-5  7 -3]]

Manual Check (A[0,0] + B[0,0]): 8
Manual Check (A[0,0] - B[0,0]): 4


In [2]:
import numpy as np

X = np.random.randint(1, 10, (3, 2))
Y = np.random.randint(1, 10, (2, 3))

print("Matrix X (3x2):\n", X)
print("Matrix Y (2x3):\n", Y)

dot_result = np.dot(X, Y)

print("\nDot Product Result (3x3):\n", dot_result)

print("\nManual Check (X[0] dot Y[:,0]):", np.dot(X[0], Y[:,0]))

Matrix X (3x2):
 [[4 5]
 [6 9]
 [2 8]]
Matrix Y (2x3):
 [[8 3 5]
 [3 9 6]]

Dot Product Result (3x3):
 [[47 57 50]
 [75 99 84]
 [40 78 58]]

Manual Check (X[0] dot Y[:,0]): 47
